
--
-- Dumping data for table `meetings`
--

LOCK TABLES `meetings` WRITE;
/*!40000 ALTER TABLE `meetings` DISABLE KEYS */;
INSERT INTO `meetings` VALUES ('AutoScaling to Ensure Survivability on the Internet',' This month Matthew Puccerella will be presenting some of his experiences with Amazon\'s AWS and web site scalability. SUMMARY: In today\'s world of access on demand, ensuring survivability is a top priority. This presentation covers an end to end solution based on Amazon\'s AWS. With Amazon AWS you can scale your environment to fit the need of your current situation. The demonstration will cover how to automatically leverage the on demand computing power of Amazon EC2 to only pay for the resources you need, when you need them.',1297213200,9,'Matthew Puccerella','http://www.meetup.com/dallasphp/events/16105151/'),('Kohana v3 MVC + Facebook','Frameworks are still one of the most popular topics in the PHP ecosystem right now, and it seems like you can\'t make a move without stepping in one.\r\n\r\nIn this month\'s meeting, Chris Benard will be demonstrating how to use the Kohana v3 MVC Framework (originally based on CodeIgniter) to make dynamic sites easily using PHP. A brief overview of MVC will be given, explaining how this design pattern will clean up your code and make it easier to reuse your own code. Kohana is a small framework (2.8 MB) packed with a ton of interesting features. A high level overview will be given by creating a blog site in real time, using features such as routing, url generation, ORM database access, and form helpers.\r\n\r\nAfter creating the blog using Kohana, the site will be enabled with Facebook features such as Facebook Connect/Login (for admin areas of the site) and Facebook Comments on the blog entries.',1294794000,10,'Chris Benard','http://www.meetup.com/dallasphp/events/15914959/'),('Upcoming','Upcoming meetup, no topic defined yet',1299632400,11,'<none>',''),('Doing More with LESS','It\'s the end of the year and there\'s no better time to pick up something new to add to your skillset for 2011. PHP developers can\'t just restrict themselves to solely the backend anymore - hybrid positions with frontend skills are more and more in demand. Jake Smith will be presenting this month about a CSS framework - the LESS framework - that lets you make more powerful CSS for your sites simpler than doing it by hand.\r\n\r\n------------- \r\n\"Doing More with LESS\" \r\nLESS is a flexible and dynamic way to develop CSS. A developer can quickly utilize CSS3 features, including browser specific implementations, with little effort. LESS is what everyone dreamed CSS could be. With such things as variables, mixins, nested rules and operations. He will show you how to use LESS to make your development process faster and more efficient. \r\n-------------\r\n\r\nMake your plans to attend now and learn about this handy, powerful tool.',1292374800,12,'Jake Smith','http://www.meetup.com/dallasphp/events/15684178/');
/*!40000 ALTER TABLE `meetings` ENABLE KEYS */;
UNLOCK TABLES;

-- Dump completed on 2011-02-23 18:43:00
